### ISSUE TITLE
Bottom part of the report problem tooltip is not visible

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/blok#196] opened 2016-10-17 07:41 UTC
latest Nightly, Linux Mint 18, Cinnamon

Sorry I cannot make a screenshot, as the icon "tooltip menu" disappears immediately as I press any key. The tooltip is cut for me under the Buttons word, without a scrollbar. It should scale according to the content dimensions.

**Comment by SoftVision-EmilPasca** [comment] 2016-10-17 08:48
@MikkCZ, thank you very much for reporting this to us.

Unfortunately this issue is a dupe of #[168](https://github.com/mozilla/blok/issues/168).

**Closed by SoftVision-EmilPasca** 2016-10-17 08:48 UTC
