### ISSUE TITLE
[Enhancement] A confirmation message should be displayed after reporting a problem or clicking the "This page works well" button

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/blok#124] opened 2016-08-26 07:38 UTC
[Affected versions]:
- Firefox 48.0 and up
- Blok 0.1.13-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Blok add-on version (0.1.13-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Visit http://edition.cnn.com/
3. Click the Blok icon from the address bar.
4. Click the "This page works well" button from the doorhanger.

[Expected result]:
- A confirmation message should be displayed informing the user that the requested action was performed. 

[Actual result]:
- The operation is performed, but no confirmation message is displayed.

[Notes]:
- The issue is also reproducible if you report a problem and click Submit, the user has no confirmation that his problem has been submitted.
- Also, maybe we should keep the doorhanger open after submitting, for the user to see those confirmations.
- Attached a screen recording of the issue goo.gl/vxRJoz.

**Comment by groovecoder** [comment] 2016-09-01 19:58
Partial dupe of https://github.com/mozilla/blok/issues/113 and requires https://github.com/mozilla/blok/pull/126 to be merged before fix.

**Closed** 2016-09-01 19:58 UTC
Labels: popup

**Comment by SoftVision-CiprianMuresan** [comment] 2016-09-08 08:59
#126 is merged, #113 is closed, but the user still doesn't get a confirmation message informing him that the requested action was performed. So you just click the "This page works well" button and the doorhanger disappears, requiring another click on the Blok icon to see the effect of the button.
In my opinion the extra click isn't necessary. 

What do you think?

**Comment by groovecoder** [comment] 2016-09-08 14:38
I vote we want Blok doorhanger to disappear as quickly as possible to get out of the user's way once they've given us input.

But I'll leave it to @johngruen to decide if that's a good final UX.
