### ISSUE TITLE
Tracking protection is not enabled even after installing

### ISSUE THREAD

**Issue by rabimba** [mozilla/blok#172] opened 2016-09-29 22:10 UTC
#### Version used: 49.0
![image](https://cloud.githubusercontent.com/assets/776740/18974159/f96def7e-8666-11e6-8e74-b22944666c0b.png)

#### Steps to reproduce: (not sure can be)

- Open Firefox (stable version)
- Goto testpilot website. Install testpilot. Enable Tracking protection
- Open reddit.com

#### Expected

Tracking protection should be enabled and user should see the blue shield saying him so

#### Actual

The blue shield icon is missing and there is no indication that tracking protection is enabled.
![image](https://cloud.githubusercontent.com/assets/776740/18974249/83db5f66-8667-11e6-8f8f-bfd19bbfde24.png)

##### Variations

Have tried it with closing firefox and reopening it again.

#### System details (if needed)

![image](https://cloud.githubusercontent.com/assets/776740/18974268/9b37f124-8667-11e6-958e-571f3fdddf4e.png)

**Comment by SoftVision-EmilPasca** [comment] 2016-09-30 12:40
I have tested this issue on Ubuntu 16.04 x64 with the latest Firefox release (49.0) and could not reproduce it.
After installing TestPilot on a new profile and enabling tracking protection, when navigating to reddit.com the blue shield icon is displayed in the address bar as enabled.

Could you please retest this using a new clean Firefox profile? If the issue isn't reproducible with a clean profile, could you also retest this with your old profile and disable the other addons one-by-one in order to see if there is any compatibility issue between Blok and the other addons.

**Comment by groovecoder** [comment] 2016-10-06 14:39
@rabimba can you check to see if this issue is the same as https://github.com/mozilla/testpilot/issues/1474? I.e., do you get the error on other Test Pilot experiment installs too? If so, we'll close this bug in favor of that one.

**Comment by groovecoder** [comment] 2016-10-11 15:14
Closing as an effect/duplicate of https://github.com/mozilla/testpilot/issues/1474. Please continue discussion there.

**Closed by groovecoder** 2016-10-11 15:14 UTC
Labels: bug, Test Pilot
