### ISSUE TITLE
The Report a problem input blocks context menu

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/blok#198] opened 2016-10-17 12:01 UTC
After choosing the problem, there is an input area to specify the problem. The input respects current spellcheck settings, but does not allow to change it via context menu. In combination with https://github.com/mozilla/blok/issues/197, there is no easy way, how to change the spellcheck dictionary here.

**Comment by groovecoder** [comment] 2016-10-17 16:06
Looks like this is a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1299371.

**Closed by groovecoder** 2016-10-17 16:06 UTC
