### ISSUE TITLE
"Submit" button is missing from the "Report a problem" panel on Ubuntu (16.04 x64)

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/blok#147] opened 2016-09-12 11:47 UTC
[Affected versions]:
- Nightly 51.0a1
- Blok v0.1.0rc3

[Affected Platforms]:
- All Linux

[Prerequisites]:
- Latest Blok add-on (v0.1.0rc3) is installed and enabled on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a website that track user actions.
2. Click on the Blok icon in the address bar.
3. Click on the "Report a problem" button and observe the panel.

[Expected result]:
- The "Submit" button is placed at the bottom of the panel.

[Actual result]:
- The "Submit" button is missing.

[Notes]:
- Added a screenshot with the issue:
![blok_issue_submit_button](https://cloud.githubusercontent.com/assets/20083658/18434775/c907570c-78f7-11e6-919f-baf81ac53fa0.jpg)

**Comment by groovecoder** [comment] 2016-09-12 13:01
Hmm ... I didn't see this but I'll check again. You might try a force-refresh? @johngruen added some new styles, but Firefox has sometimes been finicky with me about caching add-on stylesheets.

**Comment by SoftVision-PaulOiegas** [comment] 2016-09-12 15:37
Emil updated the title, he forgot to mention that this was only caught on Linux. To be more specific on Ubuntu 16.04.  
Also, I think he uses a clean profile each day for testing. So I don't think that he had something cached. But we will double check tomorrow.

**Comment by groovecoder** [comment] 2016-09-12 16:15
Hmm ... I'm able to reproduce something similar in Firefox 49 on Mac ...

<img width="877" alt="mac-blok-cnn-report-problem" src="https://cloud.githubusercontent.com/assets/71928/18443377/43385756-78da-11e6-9409-64514e067171.png">

I'll keep digging ...

**Comment by groovecoder** [comment] 2016-09-12 16:34
Well, now I'm not able to. So this seems like a flaky bug in any case. 😒

**Comment by johngruen** [comment] 2016-09-12 17:29
@groovecoder I specified very few, if any heights in my CSS...wonder if this is an issue with the page action doorhanger? I will try to repro.

**Comment by johngruen** [comment] 2016-09-12 17:45
@groovecoder seeing this in beta on a pre-my-stuff version (whatever's currently in testpilot.dev) 
<img width="415" alt="screen shot 2016-09-12 at 7 44 02 pm" src="https://cloud.githubusercontent.com/assets/3323249/18446172/669aacd4-7921-11e6-9391-dbe836b8e8ec.png">

Anyway i didn't break it, so that's a relief :)

**Comment by johngruen** [comment] 2016-09-12 17:47
@SoftVision-EmilPasca looks like there might be a second issue with the radio buttons not wrapping correctly.

@groovecoder i declared an explicit width on the labels for the radio buttons to make them bigger hit targets, while you're looking into this, there's probably a smarter way to do this.

**Comment by groovecoder** [comment] 2016-09-12 18:45
@johngruen yeah I'm getting the behavior in some older commits too, but I'm still not able to reliably reproduce. 😐

**Comment by pdehaan** [comment] 2016-09-12 18:59
@groovecoder I can take a look after lunch, if you can update the Test Pilot dev server with the latest XPI (or I can build locally, but I'm chronically lazy).

**Comment by groovecoder** [comment] 2016-09-12 19:11
http://testpilot.dev.mozaws.net/experiments/blok should be updated with the latest (1.0rc3) version of the add-on.

**Comment by groovecoder** [comment] 2016-09-12 19:29
It's weird that you saw this behavior on Nightly. In my testing I only see this issue in Firefox <=49, and John-Galt and freaktechnik in #webextensions IRC channel confirm: dynamic pageAction popup re-sizing is only available in Firefox 50+ 😢 

A hack/fix for Firefox <= 49 could be to close & re-open the popup with the new content, so I'll try that.

**Comment by pdehaan** [comment] 2016-09-12 19:35
I was unable to reproduce on Nightly 51.0a1 (2016-09-07) with the latest blok 1.0rc3:

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/18449721/31465970-78e5-11e6-8ac5-2816b92da805.png)

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/18449711/220452dc-78e5-11e6-90da-7bce3d66ea80.png)


![_r_videos_and__submit__button_is_missing_from_the__report_a_problem__panel_on_ubuntu__16_04_x64__ _issue__147_ _mozilla_blok_and_browser_console_and_new_design_for_grouped_highlights_by_piatra_ _pull_request__1153_ _mozilla_activity-stream](https://cloud.githubusercontent.com/assets/557895/18449702/14530610-78e5-11e6-9f97-e41998e6bae6.png)

**Comment by SoftVision-EmilPasca** [comment] 2016-09-13 13:51
The issue is still reproducible on the latest Nightly (51.0a1-20160913030425) with the latest Blok (v1.0rc3).

**Comment by groovecoder** [comment] 2016-09-13 15:31
Uplifting from IRC ...
```
9:35 AM <@groovecoder> jgruen: okay, after a frustrating few trials yesterday to make the page action pop-up dynamically re-size to the height of the feedback panel, I think we may need to try a less-pretty alternative … 
9:36 AM <@groovecoder> jgruen: i.e., make the main panel height equal the feedback panel with padding in its elements. The main panel pop-up will look sparse and stretched, but both panels will work
9:37 AM <@groovecoder> jgruen: and I can try to code it in a way that will detect Fx 49 vs. Fx 50 so it will look *good* in Fx 50 and be *functional* in Fx 49
9:55 AM <jgruen> groove coder … oy vey
9:55 AM <jgruen> groovecoder: ^
9:55 AM <jgruen> can i think about it for a bit
9:55 AM <@groovecoder> jgruen: yeah.
9:55 AM <jgruen> cool
9:56 AM <jgruen> one thought
9:56 AM <jgruen> split extra feedback out onto a 3rd panel
9:56 AM <@groovecoder> jgruen: I tried 3 or 4 techniques yesterday. None actually worked, and even if they had the UX would be as bad or worse than a tall main panel.
9:56 AM <@groovecoder> jgruen: hmm … good idea
9:57 AM <@groovecoder> jgruen: Let me start by trying to make the 1st main panel tall enough for feedback panel to make sure that approach even works. Then I can split the feedback panel into 2 and keep them all the same height.
9:57 AM <jgruen> cool
```
First results look alright to me (on Firefox 49):

![blok-main-panel-with-button-padding](https://cloud.githubusercontent.com/assets/71928/18480151/38ccd3fa-799d-11e6-97c6-0acd08f27bde.png)

![blok-feedback-panel-without-notes](https://cloud.githubusercontent.com/assets/71928/18480159/41defd74-799d-11e6-9ac5-9116981259f7.png)

**Comment by groovecoder** [comment] 2016-09-13 15:40
Unable to reproduce on Mac Firefox Nightly 51.0a1 2016-09-13 64-bit Blok 1.0rc3 ...

![mac-fx-51 0a1-2016-09-13-64bit-blok-1 0rc3-popup-feedback](https://cloud.githubusercontent.com/assets/71928/18480446/512e6214-799e-11e6-8e59-058645920518.png)

@pdehaan or @rbillings are you able to reproduce on Linux/Ubuntu Nightly?

**Comment by rbillings** [comment] 2016-09-13 22:40
Unfortunately I don't have a Linux VM handy- I could possibly get one if no one else has it handy.

**Comment by SoftVision-EmilPasca** [comment] 2016-09-23 13:46
I have managed to reproduce this in today's build Blok(v1.0.1) on the latest Nightly(52.0a1-20160922030437) on Ubuntu 16.04 x64, using the same steps as described before.

**Comment by groovecoder** [comment] 2016-09-23 15:17
Unable to reproduce on Mac 10.11.6 + Nightly 52.0a1 (2016-09-23) (64-bit) + Blok 1.0.1 on meetup.com, cnn.com, economist.com or reddit.com. (Probably not necessary to check more than 1 domain)

@pdehaan do you have an Ubuntu or Linux box you can try to reproduce?

**Comment by jgmize** [comment] 2016-09-23 17:56
Reproduced on Ubuntu 16.04 + Nightly 52.0a1 (2016-09-23) (64-bit) + Blok 1.0.1 on cnn.com.

**Comment by SoftVision-EmilPasca** [comment] 2016-10-10 13:24
This issue is no longer reproducible on the latest Blok build v1.0.1.

**Comment by catlee** [comment] 2016-10-11 08:47
I still have this issue on Linux + Nightly 52.0a1 (2016-10-10) + Blok 1.0.1

**Comment by SoftVision-EmilPasca** [comment] 2016-10-11 11:27
I have also managed to reproduce this after retesting it on Ubuntu 12.04 x32 + Nightly 52.0a1 (2016-10-10) + Blok 1.0.1.

**Comment by groovecoder** [comment] 2016-10-11 16:06
Okay, I'm setting up a VirtualBox VM with Ubuntu x64 so I can try to reproduce and fix this.

**Comment by groovecoder** [comment] 2016-10-11 17:06
I submitted https://github.com/mozilla/blok/pull/192 with a fix for this. Can any of the Linux users here run this branch of the add-on code to verify my fix before merge?

**Comment by SoftVision-EmilPasca** [comment] 2016-10-12 14:48
This issue is no longer reproducible on the latest build v1.0.1, retested today on Ubuntu 12.04 x32 and Ubuntu 16.04 x64 with Nightly 52.0a1 (2016-10-12).

**Comment by groovecoder** [comment] 2016-10-12 14:55
Can you try a few more Firefox versions - i.e., 49, 50, and 51? IIRC it only affected certain versions. In my case, I saw it on Firefox 49 on Ubuntu.

**Comment by SoftVision-EmilPasca** [comment] 2016-10-12 14:58
@groovecoder Sure thing, I'll test with a few more and come back with the results.

**Comment by SoftVision-EmilPasca** [comment] 2016-10-12 16:14
Still unable to reproduce after retesting on:
Ubuntu 16.04 x64 - 48.0.2, 49.0, 49.0.1, 50.0b6, 51.0a1, 51.0a2
Ubuntu 14.04 x32 - 49.0, 49.0.1, 50.0a1, 52.0a2
Ubuntu 12.04 x32 - 49.0, 49.0.1, 50.0b6, 51.0a2

**Comment by groovecoder** [comment] 2016-10-12 17:54
Wow, dang. And that's all with the add-on as enabled from
testpilot.firefox.com ?

**Comment by SoftVision-EmilPasca** [comment] 2016-10-13 07:06
Installed as a temporary add-on in about:debugging tab.

**Comment by SoftVision-EmilPasca** [comment] 2016-10-13 12:42
The issue is reproducible when enabling Tracking Protection from testpilot.firefox.com on Ubuntu 16.04 x64 with Firefox versions - 52.0a1, 51.0a2, 50.0b6,  49.0.1, 49.0.

**Comment by groovecoder** [comment] 2016-10-13 14:08
So it *is* reproducible when installing from testpilot.firefox.com, but *not* reproducible when installing the 1.0.1 .xpi via `about:debugging` ?

In either case, if you can confirm that this issue is fixed (i.e., not reproducible) on this branch of the code (via [Running the code instructions](https://github.com/mozilla/blok#running-the-code) with this branch checked out), I'd like to merge this to be sure.

**Comment by SoftVision-EmilPasca** [comment] 2016-10-13 14:19
Yes, the issue is fixed on master.
The issue is **only** reproducible when installing the addon from testpilot.firefox.com.

**Comment by groovecoder** [comment] 2016-10-13 14:26
Sorry, I meant could you confirm it's fixed (i.e., not reproducible) on the `linux-breakage-radio-147` branch.

**Closed** 2016-10-13 16:08 UTC
Labels: bug, help wanted, needs:UX, popup

**Comment by SoftVision-EmilPasca** [comment] 2016-10-17 08:45
This issue is no longer reproducible on the latest (master) build v1.0.1, retested today on Ubuntu 12.04 x32 and Ubuntu 16.04 x64 with Firefox 49.0.1 and the latest Nightly 52.0a1 (2016-10-16).
