### ISSUE TITLE
Disable built-in TP to avoid interfering with this add-on

### ISSUE THREAD

**Issue by fmarier** [mozilla/blok#12] opened 2016-06-28 21:27 UTC
We need to make sure that real TP is disabled to make sure that the breakages come from the add-on:
- `privacy.trackingprotection.enabled = false`
- `privacy.trackingprotection.pbmode.enable = false`

We should probably also detect Privacy Badger, uBlock, ABP, etc. and ask users to disable them.

**Comment by fmarier** [comment] 2016-06-28 22:17
The concern here is that if you have both TP and blok enabled, then you need to whitelist a site twice for example if you want to exempt it from any blocking. For example, if a user disables blocking on cnn.com via blok, it still won't work because TP will be blocking the resources too.

The way it works is that add-ons go first and can decide whether or not to cancel network loads. then once the add-ons are all done, we do one last check in TP just before we open a network socket.

**Comment by groovecoder** [comment] 2016-07-08 15:20
@lmorchard - can we add another broadcast channel for this? Maybe `'testpilot-aboutconfig'` for web extensions to send messages for Test Pilot to set `about:config` values?

And/or, (how) could a web extension ask Test Pilot what other add-ons are installed?

**Comment by groovecoder** [comment] 2016-07-08 15:23
@johngruen or @fmarier: do we have telemetry numbers on how many users are running with `privacy.trackingprotection.enabled = false` For the purposes of a test pilot experiment, might those numbers be low enough that we can simply ask the users who are reporting breakage if they are also running with built-in tracking protection?

**Comment by groovecoder** [comment] 2016-07-08 15:25
@johngruen @fmarier: Actually, when we ask users for feedback, we will get a telemetry ping from them. That telemetry ping should include the metadata whether or not tracking protection is enabled, right?

**Comment by lmorchard** [comment] 2016-07-08 16:36
WebExtensions are sandboxed for good security reasons, and we need to be really careful about how & what additional capabilities are granted through Test Pilot. 

I *think* the BroadcastChannel scheme is reasonably locked down to individual add-on IDs, so we can restrict what messages Test Pilot honors. But, we need to be sure there's no way for other arbitrary WebExtensions to tap into those super-powers. Telemetry pings are one thing, but prefs changes are dangerous.

That said, I think we could add those capabilities via the BroadcastChannel mechanism. I'd say rather than create a new channel, we add a `type` property to the events sent to the existing BroadcastChannel to subdivide it between Telemetry pings and additional things like pref change & add-on list requests.

**Comment by groovecoder** [comment] 2016-07-08 17:21
Yeah that makes sense - we should be extra careful about what messages Test Pilot can receive from web extensions.

Deny-by-default with a small enumerated list of specific `types` of messages/events we allow sounds like the best way.

**Comment by fmarier** [comment] 2016-07-08 22:52
> do we have telemetry numbers on how many users are running with `privacy.trackingprotection.enabled = false`

We do, it's the first one in here: https://wiki.mozilla.org/Security/Tracking_protection#Telemetry

**Comment by groovecoder** [comment] 2016-07-08 22:54
So, [approx. 1.45% of sessions have tracking protection enabled](https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2016-04-25&keys=__none__!__none__!__none__&max_channel_version=aurora%252F47&measure=TRACKING_PROTECTION_ENABLED&min_channel_version=null&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2016-03-08&table=1&trim=1&use_submission_date=0)?

**Comment by fmarier** [comment] 2016-07-08 22:57
It depends on the channel, it's 7% on Nightly and < 1% on Beta.

**Comment by fmarier** [comment] 2016-07-09 17:37
Instead of disabling the built-in TP (i.e. changing a pref), another approach would be to detect it (i.e. reading a pref only) and then refuse to run the experiment until the user has turned it off.

**Comment by groovecoder** [comment] 2016-07-12 17:50
@lmorchard - what do you think about adding Test Pilot code for these new `type`s of messages:

* `{type: 'prefValueRequest', pref: 'privacy.trackingprotection.enabled'}
* `{type: 'addonListRequest'}

?

**Comment by lmorchard** [comment] 2016-07-13 18:22
> what do you think about adding Test Pilot code for these new types of messages

Those look just read-only, and so way less worrisome than changing prefs. Been swamped with the latest Test Pilot sprint this week, but can look into doing that stuff soon. If you get a minute, maybe file an issue on our repo and we can prioritize it?

**Comment by groovecoder** [comment] 2016-07-13 21:25
Filed https://github.com/mozilla/testpilot/issues/1068

**Comment by groovecoder** [comment] 2016-07-14 15:56
@lmorchard: is there a way for Test Pilot (add-on and/or server) to only show the Blok experiment to users who:

* Have `privacy.trackingprotection.enabled` = `false`
**AND**
* Do **NOT** have another blocking add-on

?

If so, maybe the best way to do this is to let Test Pilot filter users out of the Blok experiment altogether?

**Comment by groovecoder** [comment] 2016-08-02 16:36
@johngruen - yesterday you mentioned we may not want to do this and we might find another way to limit the experiment to users without a tracking add-on? So maybe this should be closed and there should be an up-stream issue in Test Pilot to show certain experiments only to users without certain other add-ons?

**Comment by groovecoder** [comment] 2016-08-08 14:02
@johngruen - weekly ping; did you say you want to find a way to limit this experiment to users who do **not** having another TP add-on installed? If so, that's probably all to-do in the Test Pilot code-base.

**Comment by groovecoder** [comment] 2016-08-08 19:09
Step 1: investigate what happens when running multiple blocking add-ons. I'll report back here.

**Comment by groovecoder** [comment] 2016-08-08 19:10
Step 2: Investigate how Test Pilot might warn users of incompatible addons. (See https://github.com/mozilla/testpilot/issues/944)

**Comment by groovecoder** [comment] 2016-08-09 14:52
Results of multiple blocking add-ons:

1. **Blok + Private Browsing Window**: No conflict. Blok records and blocks all the same tracker requests, and telemetry pings work. Blok intercepts requests before they get to the platform level.

2. **Blok + "Always use Private Browsing Mode"**: No conflict Blok records and blocks all the same tracker requests, and telemetry pings work. Blok intercepts requests before they get to the platform level.

3. **Blok + Adblock Plus**: Blok records and blocks 50% fewer tracker requests; telemetry pings still work.

4. **Blok + Ghostery**: No conflict. Blok records and blocks all the same tracker requests, and telemetry pings work. Ghostery **also** reports on the tracker requests, and its details are a bit different, which I assume is caused by the different lists they use.

5. **Blok + uBlock Origin**: Blok records and blocks 50% fewer tracker requests; telemetry pings still work.

6. **Blok + Adblock Plus + Ghostery + uBlock Origin**: Blok records and blocks ~1/3 of the tracker requests; telemetry pings still work

So, there certainly seems to be conflict between blocking add-ons. A couple of theories:

* **SDK/XPI add-ons vs. Web Extension add-on**
* Plain old race conditions

**Comment by groovecoder** [comment] 2016-08-09 19:51
Idea: If Telemetry ping data includes meta-data of the other add-ons the user has installed, we could filter out the conflicting data when we run the reports?

**Comment by groovecoder** [comment] 2016-09-07 15:30
@johngruen In emails we discussed filtering out these users on the backend/Telemetry reports. If that's fine, let's close this issue and open a ... bug for that?

**Comment by groovecoder** [comment] 2016-09-08 21:33
Assigning to @johngruen to make final decision that we can filter Telemetry data out from users with other blockers installed and active.

**Comment by johngruen** [comment] 2016-09-09 15:18
@groovecoder this is upstream for sure. Will keep it open until we finalize the work in Test Pilot

**Comment by johngruen** [comment] 2016-09-09 15:20
cf
https://github.com/mozilla/testpilot/issues/1333
https://github.com/mozilla/testpilot/issues/944

**Comment by groovecoder** [comment] 2016-09-15 15:36
@johngruen: This is listed in the first launch milestone, but have we decided that we don't **need** to fix https://github.com/mozilla/testpilot/issues/1333 for launch? I.e., we can filter out incompatible add-on users from the Telemetry reports, right?

**Comment by johngruen** [comment] 2016-11-01 17:07
@groovecoder we're not passing installed add-ons into our ping, but we do have UI warning people of incompatabilities

**Comment by johngruen** [comment] 2016-11-01 17:07
Since we're not changing anything else here @groovecoder we can probably close this

**Comment by groovecoder** [comment] 2016-11-01 17:26
Yeah, that's fine. I've got https://github.com/mozilla/testpilot_metrics/issues/11 filed to filter users with built-in TP enabled out of the experiment reports.

**Closed by groovecoder** 2016-11-01 17:26 UTC
Labels: background, Test Pilot
