### ISSUE TITLE
Errors in error console

### ISSUE THREAD

**Issue by wagnerand** [mozilla/blok#221] opened 2017-01-08 12:03 UTC
I am getting the following errors on startup in latest aurora (2017-01-08):

background.bundle.js:353
focusedWindow is undefined 

background.bundle.js:362
tab is undefined

**Comment by wagnerand** [comment] 2017-01-08 12:04
Oh, dupe of #220.

**Comment by groovecoder** [comment] 2017-01-30 16:47
Closing as dupe of #220. Sorry for the bug. 😢

**Closed by groovecoder** 2017-01-30 16:47 UTC
